# Services
services:
  # Nginx Service
  nginx1:
    container_name: nginx1
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/public
    depends_on:
      - php1
  #      - mysql1

  # PHP Service
  php1:
    container_name: php1
    build: ./.docker/php
    volumes:
      - ./public:/var/www/public
      - ./src:/var/www/src
      - ./vendor:/var/www/vendor
  #    depends_on:
  #      - mysql1

  # MySQL Service
#  mysql1:
#    container_name: mysql1
#    image: mysql
#    volumes:
#      - ./mysql-data:/var/lib/mysql
#    environment:
#      - MYSQL_ROOT_PASSWORD=root
#      - MYSQL_DATABASE=mydb
#      - MYSQL_USER=user
#      - MYSQL_PASSWORD=123
#    networks:
#      - network1

#  phpmyadmin1:
#    container_name: phpmyadmin1
#    image: phpmyadmin
#    ports:
#      - 1500:80
#    environment:
#      - PMA_HOST=mysql1
#    networks:
#      - network1
#    depends_on:
#      - mysql1